### DISCUSSION TITLE
Github Actions 워크플로우: Issue Branch Deploy

### DISCUSSION THREAD

**Discussion by dnlpys** [minhyeok0328/next-loop#43] [General]
![스크린샷 2024-11-01 16 33 44](https://github.com/user-attachments/assets/f31b2535-4294-4284-8f01-e2ea1f8efee3)

### 개요
- Pull Request가 main 브랜치에 머지될 때 특정 컴포넌트의 변경사항을 자동으로 감지하고 배포하는 자동화된 프로세스를 구현합니다.
---
### 트리거 조건
- 이벤트: Pull Request closed
- 대상 브랜치: main
- 모니터링 경로:
  -  airflow/**
  -  backend/**
  -  kafka/**
  -  mariadb/**
 ---
### Job
- detect-changes:
dorny/paths-filter@v2 액션을 사용하여 각 컴포넌트 디렉토리의 변경사항을 감지
- deploy-mariadb : (예시)
detect-changes 작업에서 mariadb 컴포넌트의 변경이 감지된 경우, MariaDB 관련 변경사항을 배포
---
```yaml
name: Issue Branch Deploy

on:
  pull_request:
    types: [closed]
    branches: 
      - 'main'
    paths:
      - 'airflow/**'
      - 'backend/**'
      - 'kafka/**'
      - 'mariadb/**'

jobs:
  detect-changes:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    outputs:
      airflow: ${{ steps.filter.outputs.airflow }}
      backend: ${{ steps.filter.outputs.backend }}
      kafka: ${{ steps.filter.outputs.kafka }}
      mariadb: ${{ steps.filter.outputs.mariadb }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Filter paths for each component
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            airflow:
              - 'airflow/**'
            backend:
              - 'backend/**'
            kafka:
              - 'kafka/**'
            mariadb:
              - 'mariadb/**'
              
  deploy-mariadb:
    needs: detect-changes
    if: needs.detect-changes.outputs.mariadb == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_MARIADB_HOST: ${{ secrets.SERVER_MARIADB_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H $SERVER_MARIADB_HOST >> ~/.ssh/known_hosts
      - name: Test Second SSH Connection
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_MARIADB_HOST: ${{ secrets.SERVER_MARIADB_HOST }}
        run: |
          ssh -i ~/.ssh/deploy_key $SERVER_USERNAME@$SERVER_MARIADB_HOST "echo test"

      - name: Deploy mariadb Changes      
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_MARIADB_HOST: ${{ secrets.SERVER_MARIADB_HOST }}
        run: |
          ssh -i ~/.ssh/deploy_key $SERVER_USERNAME@$SERVER_MARIADB_HOST "\
            cd ~/mariadb-production && \
            git fetch origin && \
            git pull origin 26-issue-2 && \
            git checkout 26-issue-2 \
          "
```
- 인스턴스 홈디렉토리에 production 경로생성
- ~/production 경로에 main브랜치 코드 배포.
- Set up SSH: 깃허브서버에서 (플랫폼)인스턴스로 연결하는 job
- Test Second SSH Connection: ssh 연결 test job (test 완료 후 삭제)
- Deploy mariadb Changes: main브랜치로 pr, merge된 코드 업데이트 해주는 job
---

### 인스턴스에서 해줘야하는 초기 설정
```
# 초기 설정시 1회 (ex. mariadb-instance)
mkdir -p ~production
cd ~/production
git init
git config --local user.name "사용자 이름"
git config --local user.email "이메일 주소"
git remote add origin ${REPO_URL}
git config core.sparseCheckout true
echo 'mariadb/*' > .git/info/sparse-checkout
```
