### DISCUSSION TITLE
Mariadb Setup 가이드

### DISCUSSION THREAD

**Discussion by dnlpys** [minhyeok0328/next-loop#44] [General]
# GCP에서 MariaDB 컨테이너 실행하기 

## 목차
1. [사전 준비사항](#사전-준비사항)
2. [파일 구조](#파일-구조)
3. [설정 파일 설명](#설정-파일-설명)
4. [실행 방법](#실행-방법)
5. [설정 상세 설명](#설정-상세-설명)
6. [문제 해결](#문제-해결)

## 사전 준비사항
- GCP(Google Cloud Platform) 계정
- GCP 인스턴스에 설치되어 있어야 하는 것들:
  - Docker
  - Docker Compose
  - Git (선택사항)

## 파일 구조
```
your-project-folder/
├── docker-compose.yml    # 도커 컴포즈 설정 파일
├── my.cnf               # MariaDB 설정 파일
└── init.sql            # (필요한 경우) 초기 데이터베이스 설정 파일
```

### 1. docker-compose.yml 파일 설명
```yaml
services:
  mariadb:
    image: mariadb:11.5.2    # MariaDB 버전 11.5.2 사용
    container_name: mariadb   # 컨테이너 이름
    environment:             # 환경 변수 설정
      MYSQL_DATABASE: next-loop     # 생성될 데이터베이스 이름
      MYSQL_USER: next-loop        # 생성될 사용자 이름
      MYSQL_PASSWORD: 1234         # 사용자 비밀번호
      MYSQL_ROOT_PASSWORD: 1234    # root 사용자 비밀번호
```

### 2. my.cnf 파일 설명
```ini
[mysqld]
character-set-server = utf8mb4          # 한글 지원을 위한 문자셋 설정
collation-server = utf8mb4_unicode_ci   # 정렬 규칙 설정

max_connections = 500                   # 최대 동시 연결 수
innodb_buffer_pool_size = 1G           # InnoDB 버퍼 풀 크기
innodb_log_file_size = 256M            # 로그 파일 크기

slow_query_log = 1                     # 느린 쿼리 로깅 활성화
long_query_time = 2                    # 2초 이상 걸리는 쿼리를 느린 쿼리로 기록
```

## 실행 방법

1. GCP 인스턴스에 접속
```bash
ssh your-username@your-instance-ip
```

2. 프로젝트 디렉토리 생성 및 이동
```bash
mkdir mariadb-project
cd mariadb-project
```

3. 설정 파일 생성
- `docker-compose.yml` 파일 생성
- `my.cnf` 파일 생성
- (필요한 경우) `init.sql` 파일 생성

4. Docker Compose 실행
```bash
docker-compose up -d
```

5. 실행 확인
```bash
docker container ls
docker logs mariadb
```

### 1. 볼륨 설정
```yaml
volumes:
  - mariadb_data:/var/lib/mysql        # 데이터 영구 저장
  - ./my.cnf:/etc/mysql/conf.d/my.cnf  # MariaDB 설정 파일
```
- `mariadb_data`: 데이터베이스 데이터를 영구적으로 저장
- 컨테이너가 삭제되어도 데이터는 보존됨

### 2. 네트워크 설정
```yaml
networks:
  - mariadb_network
```
- 다른 컨테이너와 통신할 수 있도록 네트워크 구성

### 3. 포트 설정
```yaml
ports:
  - "3306:3306"
```
- 호스트의 3306 포트를 컨테이너의 3306 포트와 연결

### 4. 상태 체크 설정
```yaml
healthcheck:
  test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  interval: 10s
  timeout: 5s
  retries: 5
```
- 10초마다 데이터베이스 상태 확인
- 5번 재시도 후에도 실패하면 문제가 있는 것으로 판단

### 1. 컨테이너가 시작되지 않는 경우
```bash
# 로그 확인
docker logs mariadb

# 컨테이너 상태 확인
docker container ls -a
```

### 2. 데이터베이스 접속이 안되는 경우
- 방화벽 설정 확인 (GCP 콘솔에서)
- 3306 포트가 열려있는지 확인
```bash
netstat -tuln | grep 3306
```

### 3. 권한 문제가 발생하는 경우
```bash
# 컨테이너 내부 접속
docker exec -it mariadb bash

# MariaDB 접속
mysql -u root -p

# 권한 확인
SHOW GRANTS FOR 'next-loop'@'%';
```
