### DISCUSSION TITLE
Github Actions 워크플로우: workflow_dispatch

### DISCUSSION THREAD

**Discussion by dnlpys** [minhyeok0328/next-loop#46] [Ideas]
## 테스트 환경
- GCP instance: E2.standard-4 (vCPU 4개, RAM 16GB)
- Github Actions

## source code배포 전략
- 인스턴스의 service.dev 환경에서 개발 및 테스트
- github에 source code 푸쉬
- github actions로 인스턴스의 service.production으로 배포
- main에 pr된 source code가 merge될 경우에 자동 배포

### issue
- 배포 전략으로는 main에 pr이 merge될 경우 반드시 source code가 배포되는 강한 결합성을 갖는다.
- workflow_dispatch기능을 사용하여 결합성을 낮추고 확장성, 유연성, 재사용성을 제고
---
워크 플로우를 나눠서,
1번 워크플로우에서는 pr이 머지 되고 후속 작업을 위한 준비만 수행하고 대기
2번 워크플로우에서는 수동 트리거에 의해서 배포 워크플로우 실행
2단계에 걸쳐 결합성을 낮출수 있지만,

github actions의 workflow_dispatch기능을 사용하면 on: 섹션에 workflow_dispatch:을 추가하여 쉽게 기능구현 가능함
```yaml
name: Issue Branch Deploy

on:
  pull_request:
    types: [closed]
    branches: 
      - 'main'
    paths:
      - 'airflow/**'
      - 'backend/**'
      - 'kafka/**'
      - 'mariadb/**'
  workflow_dispatch:  # 수동 트리거 추가

jobs:
  detect-changes:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    outputs:
      airflow: ${{ steps.filter.outputs.airflow }}
      backend: ${{ steps.filter.outputs.backend }}
      kafka: ${{ steps.filter.outputs.kafka }}
      mariadb: ${{ steps.filter.outputs.mariadb }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Filter paths for each component
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            airflow:
              - 'airflow/**'
            backend:
              - 'backend/**'
            kafka:
              - 'kafka/**'
            mariadb:
              - 'mariadb/**'

  deploy-mariadb:
    needs: detect-changes
    if: needs.detect-changes.outputs.mariadb == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_MARIADB_HOST: ${{ secrets.SERVER_MARIADB_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H $SERVER_MARIADB_HOST >> ~/.ssh/known_hosts

      - name: Test Second SSH Connection
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_MARIADB_HOST: ${{ secrets.SERVER_MARIADB_HOST }}
        run: |
          ssh -i ~/.ssh/deploy_key $SERVER_USERNAME@$SERVER_MARIADB_HOST "echo test"

      - name: Deploy mariadb Changes      
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_MARIADB_HOST: ${{ secrets.SERVER_MARIADB_HOST }}
        run: |
          ssh -i ~/.ssh/deploy_key $SERVER_USERNAME@$SERVER_MARIADB_HOST "\
            cd ~/mariadb-production && \
            git fetch origin && \
            git pull origin 26-issue-2 && \
            git checkout 26-issue-2 \
          "

```
