### DISCUSSION TITLE
grafana, prometheus 모니터링

### DISCUSSION THREAD

**Discussion by imella0707** [minhyeok0328/next-loop#68] [General]
# 사전 준비사항
- GCP(Google Cloud Platform) 계정
- GCP 인스턴스에 설치되어 있어야 하는 것들:
  - Docker
  - Docker Compose
  - Git (선택사항)

# dowhat-kafka-1 
## 서버 파일 구조 
production/
     └── kafka
             └──docker-compose.jmx-exporter1.yml # 기존 docker-compose파일이 있어서 구별하기 위해 jmx버전 이름을 붙임.  

## docker-compose.jmx-exporter1.yml
```
volumes:
  kafka_volume:
    driver: local

networks:
  kafka_network:
    name: kafka_network
    driver: bridge

services:
  kafka:
    image: apache/kafka:3.7.1
    container_name: kafka-cluster-1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@10.178.0.3:9093,2@10.178.0.7:9093,3@10.178.0.9:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.178.0.3:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_RETENTION_MS: 432000 # 5일
      CLUSTER_ID: 'jaShGO9YR12vntLHlWQQBA'
    networks:
      - kafka_network
    volumes:
      - kafka_volume:/var/lib/kafka/data

  jmx-exporter: 
    image: bitnami/jmx-exporter:0.20.0
    container_name: jmx-exporter-1
    environment:
      - JVM_OPTS=-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=5556:/opt/jmx-exporter/config.yaml
    ports:
      - "5556:5556"
    networks:
      - kafka_network

# 1111
```

# dowhat-kafka-2 
## 서버 파일 구조 

production/
     └── kafka
             └──docker-compose.jmx-exporter2.yml # 기존 docker-compose파일이 있어서 구별하기 위해 jmx버전 이름을 붙임.  

## docker-compose.jmx-exporter2.yml
``` 
volumes:
  kafka_volume:
    driver: local

networks:
  kafka_network:
    name: kafka_network
    driver: bridge

services:
  kafka:
    image: apache/kafka:3.7.1
    container_name: kafka-cluster-2
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@10.178.0.3:9093,2@10.178.0.7:9093,3@10.178.0.9:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.178.0.7:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_RETENTION_MS: 432000 # 5일
      CLUSTER_ID: 'jaShGO9YR12vntLHlWQQBA'
    networks:
      - kafka_network
    volumes:
      - kafka_volume:/var/lib/kafka/data

  jmx-exporter:
    image: bitnami/jmx-exporter:0.20.0
    container_name: jmx-exporter-2
    environment:
      - JVM_OPTS=-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=5556:/opt/jmx-exporter/config.yaml
    ports:
      - "5556:5556"
    networks:
      - kafka_network

# 2222
```

# dowhat-kafka-3
## 서버 파일 구조 

production/
     └── kafka
             └──docker-compose.jmx-exporter3.yml # 기존 docker-compose파일이 있어서 구별하기 위해 jmx버전 이름을 붙임.  

## docker-compose.jmx-exporter3.yml
```
volumes:
  kafka_volume:
    driver: local

networks:
  kafka_network:
    name: kafka_network
    driver: bridge

services:
  kafka:
    image: apache/kafka:3.7.1
    container_name: kafka-cluster-3
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@10.178.0.3:9093,2@10.178.0.7:9093,3@10.178.0.9:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.178.0.9:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_RETENTION_MS: 432000 # 5일
      CLUSTER_ID: 'jaShGO9YR12vntLHlWQQBA'
    networks:
      - kafka_network
    volumes:
      - kafka_volume:/var/lib/kafka/data


  jmx-exporter:
    image: bitnami/jmx-exporter:0.20.0
    container_name: jmx-exporter-3
    environment:
      - JVM_OPTS=-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=5556:/opt/jmx-exporter/config.yaml
    ports:
      - "5556:5556"
    networks:
      - kafka_network

# 3333
```

# monitoring 
## 서버 파일 구조 
monitoring/
├── docker-compose.yml # 모니터링 관련 도커 컴포즈 설정 파일 
├── prometheus.yml # 프로메테우스 관련 파일 
└── READE.md # 포트번호, 패스워드 관련 내용

## prometheus.yml

```
version: '3.8'
services:
      
  prometheus:
    image: prom/prometheus:v2.54.1  # 버전 명시 
    platform: linux/amd64
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus 설정 파일 마운트
      - prometheus-storage:/prometheus  # Prometheus 데이터를 저장할 볼륨
    
    networks:
      - kafka_network # 다른 서버에서 카프카 네트워크를 사용중이니까 같은 네트워크로  다 묶어주기 
      
  grafana:
    image: grafana/grafana:11.0.6
    platform: linux/amd64
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always
    networks:
      - kafka_network

volumes:
  prometheus-storage:
  grafana-storage:

networks:
  kafka_network:
    name: kafka_network
    driver: bridge
```

#node-exporter 설명

- airflow exporter, statsd-exporter와 달리 push방식
  - 모니터링하고자 하는 각 서버에 설치해야됨.  따라서 각 서버의 docker-compose.yml파일 내용을 수정해줘야 함.

# Prometheus 설명
- 데이터 수집 방식이 pull방식임 
  - 각 서버마다 설치할 필요 없고 monitoring서버에만 prometheus를 설치하면 됨. 
  - Logstash나 Telegraf처럼 Pushing 방식보다 모니터링 서버 장애가 미치는 영향도가 적은 편임. 
  - 간단한 key-value 형태의 메트릭을 기반으로 집계 및 저장 기능을 갖추고 있음. 
![image](https://github.com/user-attachments/assets/ea0a25f1-59b6-4b81-bfbc-d98d0047587b)

# Grafana 설명
- Grafana Labs가 개발한 오픈소스 인터랙티브 데이터 시각화 플랫폼
- 사용자가 하나의 대시보드(또는 여러 대시보드)로 통합된 차트와 그래프를 통해 데이터를 확인할 수 있어 데이터를 손쉽게 해석하고 이해할 수 있음. 
- 메트릭 지표 표현 시 Promql을 사용 

![image](https://github.com/user-attachments/assets/c3b38a9d-a591-47f4-bf55-a2025e15dcec)
